---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: database
type: Opaque
data:
  mongodb-root-password: c2VjcmV0bw==
  mongodb-password: c2VjcmV0bw==
  mongodb-replica-set-key: c2VjcmV0bw==
