apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ENV_IMAGE
          ports:
            - containerPort: 3000
          env:
            - name: APP
              value: API

            - name: DATABASE_URI
              value: ENV_DATABASE_URI
            - name: TURN_DATABASE_URI
              value: ENV_TURN_DATABASE_URI
          resources:
            requests:
              cpu: 150m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1800Mi
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 3000
  type: NodePort

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 1500Mi