apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 1
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: ENV_IMAGE
          ports:
            - containerPort: 3000
          env:
            - name: APP
              value: FRONT

            - name: DATABASE_URI
              value: ENV_DATABASE_URI
            - name: TURN_DATABASE_URI
              value: ENV_TURN_DATABASE_URI
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool

---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: default
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 3000
  type: NodePort

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: front
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 175Mi